DROP SEQUENCE PERSON_SEQ;
CREATE SEQUENCE PERSON_SEQ NOCACHE;

DROP TABLE PERSON;
CREATE TABLE PERSON(
	PERSON_NO 		NUMBER NOT NULL,
	NAME			VARCHAR2(50 BYTE) NOT NULL,
	AGE				NUMBER NOT NULL,
	GENDER			VARCHAR2(5 BYTE),
	MODIFIED_DATE	DATE,
	CREATED_DATE	DATE NOT NULL,
	CONSTRAINT PK_PERSON PRIMARY KEY(PERSON_NO)
);

INSERT INTO PERSON VALUES(PERSON_SEQ.NEXTVAL, '강호동', 55, 'M', NULL, SYSDATE);
